In [1]:
import numpy as np

In [2]:
arr = np.array(20)

In [6]:
# checking the dimension of the attribute by the ndim attribute 

In [5]:
arr.ndim

0

### Creating 1-D array

In [7]:
arr = np.array([1, 5, 19])

In [8]:
arr.ndim

1

In [9]:
arr

array([ 1,  5, 19])

### Creating 2-D array

* Representing Matrix or 2nd order

In [11]:
arr = np.array([[1, 2, 6], [2, 3, 5]])

In [12]:
arr.ndim

2

In [14]:
arr

array([[1, 2, 6],
       [2, 3, 5]])

In [17]:
mat = np.mat(np.array([[5, 1, 15], [1, 81, 1]]))

In [18]:
mat

matrix([[ 5,  1, 15],
        [ 1, 81,  1]])

In [19]:
type(mat)

numpy.matrix

### Creating 3-D array

In [20]:
# 2D element behave as a element

In [25]:
arr = np.array([[[1, 3, 5], [3, 5, 6], [1, 25, 5]], [[5, 25, 22], [58, 58, 6], [1, 1, 5]]])

In [26]:
arr

array([[[ 1,  3,  5],
        [ 3,  5,  6],
        [ 1, 25,  5]],

       [[ 5, 25, 22],
        [58, 58,  6],
        [ 1,  1,  5]]])

In [27]:
type(arr)

numpy.ndarray

In [28]:
arr.ndim

3

## Creating higher dimension arrays

In [30]:
arr = np.array([1, 2, 4], ndmin = 5)

In [31]:
arr

array([[[[[1, 2, 4]]]]])

In [36]:
arr.ndim

5

### Knowing the shape 

In [38]:
arr.shape

(1, 1, 1, 1, 3)

In [39]:
arr = np.array([[[1, 3, 5], [3, 5, 6], [1, 25, 5]], [[5, 25, 22], [58, 58, 6], [1, 1, 5]]])

In [40]:
arr.shape

(2, 3, 3)