In [1]:
import numpy as np

## Random number generator 

### Randit: Generating the random number 
* provide maximum number

In [14]:
np.random.randint(-20, -1)

-17

In [20]:
a = np.random.randint(1, 401, (2, 2, 2))

In [21]:
a

array([[[182,  81],
        [ 66,  57]],

       [[339, 386],
        [297, 296]]])

In [22]:
# rand -------> for generating random float from 0 to 1

In [26]:
np.random.rand()

0.6100290567427303

In [27]:
np.random.rand(5, 4)

array([[0.44539319, 0.57716032, 0.98147703, 0.78170556],
       [0.36923868, 0.80038434, 0.91131206, 0.82122173],
       [0.35581732, 0.18101342, 0.91900985, 0.4076452 ],
       [0.54678125, 0.27557319, 0.66940926, 0.97327178],
       [0.75398879, 0.67121064, 0.38852866, 0.69168491]])

In [28]:
np.random.rand(3, 2, 2)

array([[[0.13620929, 0.0070259 ],
        [0.0438617 , 0.29050727]],

       [[0.89966458, 0.38529641],
        [0.76547729, 0.66948448]],

       [[0.90251046, 0.01848622],
        [0.51449974, 0.05835638]]])

In [42]:

a    = np.random.randint(200, size = (2, 2))
b = np.random.rand(2, 2)

In [43]:
a + b

array([[ 68.36122022,   2.29784181],
       [105.23103944, 144.49963329]])

### Choice

In [44]:
# choice =========> generating the random value base on the choices

In [52]:
x = np.random.choice([1, 2, 4, 5])

In [53]:
x

2

In [57]:
y = np.random.choice([1, 2, 3, 4, 5], size = (3, 3))
y

array([[3, 1, 4],
       [2, 4, 5],
       [3, 3, 2]])

In [58]:
# by choice =======> we can specify the probablity of each choice
# the sum of probability should be 1

In [62]:
z = np.random.choice([1, 2, 6, 8, 9], p = [0.7, 0.1, 0.1, 0.05, 0.05], size = (3, 3))
z

array([[1, 1, 1],
       [1, 9, 1],
       [1, 1, 6]])