### Indexing the higher dimension arrays

In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 5, 11], [33, 91, 9], [25, 91, 92], [86, 65, 42]])

In [3]:
arr.ndim

2

In [4]:
arr

array([[ 1,  5, 11],
       [33, 91,  9],
       [25, 91, 92],
       [86, 65, 42]])

In [5]:
arr.shape

(4, 3)

In [6]:
arr[1]

array([33, 91,  9])

In [7]:
arr[1][1]

91

In [8]:
arr[1, 1]

91

In [9]:
arr

array([[ 1,  5, 11],
       [33, 91,  9],
       [25, 91, 92],
       [86, 65, 42]])

In [10]:
arr[-3][-1]

9

In [11]:
# 3d Arrays

In [12]:
ar = np.array([[[48, 97, 46], [14, 82, 14]], [[5, 68, 98], [62, 33, 90]]])

In [13]:
ar

array([[[48, 97, 46],
        [14, 82, 14]],

       [[ 5, 68, 98],
        [62, 33, 90]]])

In [14]:
ar[1]

array([[ 5, 68, 98],
       [62, 33, 90]])

In [15]:
ar[1, 1]

array([62, 33, 90])

In [16]:
ar[1, 1, 1]

33

In [18]:
# high dimensinon arry

aaa = np.array(([1, 5, 88]), ndmin = 5)

In [19]:
aaa

array([[[[[ 1,  5, 88]]]]])

In [20]:
aaa.ndim

5

In [21]:
aaa[0, 0, 0, 0, 1]

5