### Shape: shape of an array is the no of elements in each dimension

In [2]:
import numpy as np

In [3]:
# Reshape
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [4]:
arr.shape

(2, 4)

In [5]:
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
a3 = np.array([[[1, 2, 3, 90], [4, 5, 6, 91]], [[7, 8, 9, 82], [10, 11, 12, 93]], [[81, 91, 95, 96], [97, 98, 99, 100]]])

In [12]:
print(a3)

[[[  1   2   3  90]
  [  4   5   6  91]]

 [[  7   8   9  82]
  [ 10  11  12  93]]

 [[ 81  91  95  96]
  [ 97  98  99 100]]]


In [13]:
a3

array([[[  1,   2,   3,  90],
        [  4,   5,   6,  91]],

       [[  7,   8,   9,  82],
        [ 10,  11,  12,  93]],

       [[ 81,  91,  95,  96],
        [ 97,  98,  99, 100]]])

In [14]:
a3.shape

(3, 2, 4)

In [15]:
an = np.array([1, 2, 3, 4], ndmin = 5)

In [16]:
an.shape

(1, 1, 1, 1, 4)

## Reshaping the array
* By reshpaing we can add or remove dimension or change the no of elements in each dimension

In [30]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
a.shape

(24,)

In [32]:
a.ndim

1

In [33]:
# Reshaping the element 
a.reshape(6, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [34]:
a2d = a.reshape(6, 4)

In [35]:
a2d.ndim

2

### Reshape in 3-D

#### 3d array reshape(a, b, c) = a is no of batches, b is no of rows, c is no of column

In [36]:
a3d = a.reshape(2, 6, 2)

In [37]:
a3d

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

## 3D

In [38]:
xyz = a.reshape(2, 2, 2, 3)

In [39]:
xyz

array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]]])

## Unknown dimensions

In [40]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [41]:
a.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
a.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [43]:
a.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [44]:
a.reshape(3, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
a.reshape(6, -1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [48]:
a.reshape(-1, 4, 6)

array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])