In [1]:
import numpy as np

### Arithmetic function

In [2]:
# addition

a = [2, 9, 10, 11, 12]
b = [1, 2, 4, 8, 19]

c = a+b
c

[2, 9, 10, 11, 12, 1, 2, 4, 8, 19]

In [4]:
d = []

for i, j in zip(a, b):
    d.append(i+j)
d

[3, 11, 14, 19, 31]

In [6]:
ara = np.array(a)
arb = np.array(b)
arc = ara - arb
arc

array([ 1,  7,  6,  3, -7])

In [7]:
ard = ara*arb
ard

array([  2,  18,  40,  88, 228])

In [8]:
list(ard)

[2, 18, 40, 88, 228]

In [9]:
are = ara/arb
are

array([2.        , 4.5       , 2.5       , 1.375     , 0.63157895])

In [10]:
arf = ara**arb
arf

array([        2,        81,     10000, 214358881,         0])

In [11]:
# it need to have same length

In [12]:
# operations not having same length produce error

In [13]:
arx = ara//arb
arx

array([2, 4, 2, 1, 0])

In [14]:
ara%3

array([2, 0, 1, 2, 0], dtype=int32)

In [15]:
np.sqrt(114)

10.677078252031311

In [17]:
x = np.sqrt(ara)

In [18]:
x

array([1.41421356, 3.        , 3.16227766, 3.31662479, 3.46410162])