### Infinity and Nan

In [1]:
import numpy as np

In [2]:
np.array(3)/0

C:\Users\Dell\AppData\Local\Temp/ipykernel_8952/48870926.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array(3)/0


inf

In [4]:
a = np.inf

In [5]:
a

inf

In [6]:
b = np.nan

In [7]:
b

nan

### Dot Product

In [8]:
ara = np.array([1, 3, 5, 10])
arb = np.array([5, 8, 12, 13])


In [9]:
ara.dot(arb)

219

In [11]:
are = np.array([[1, 3, 5, 23], [9, 3, 87, 1]])

In [12]:
are

array([[ 1,  3,  5, 23],
       [ 9,  3, 87,  1]])

In [13]:
are.T

array([[ 1,  9],
       [ 3,  3],
       [ 5, 87],
       [23,  1]])

### min, max, mean, std values

In [14]:
ard = np.array([3, 4, 92, 28, -1, -28, 1448, 1444, -2000])

In [16]:
ard.min()

-2000

In [17]:
ard.max()

1448

In [18]:
ard.argmin()

8

In [19]:
ard.argmax()

6

In [20]:
ard.mean()

110.0

In [21]:
ard.std()

947.6871260542104

In [22]:
ard.sort()

In [23]:
ard

array([-2000,   -28,    -1,     3,     4,    28,    92,  1444,  1448])

### Rounding Function

In [24]:
ar = np.array([0.4, 0.21, 0.88881, 0.00000022, 3.58, 88.285389775, -1.8777891266])

In [25]:
ar

array([ 4.00000000e-01,  2.10000000e-01,  8.88810000e-01,  2.20000000e-07,
        3.58000000e+00,  8.82853898e+01, -1.87778913e+00])

In [26]:
ar.round(1)

array([ 0.4,  0.2,  0.9,  0. ,  3.6, 88.3, -1.9])

In [27]:
np.round(2.1255555, 3)

2.126

In [29]:
# rounded to nearest smaller integer
np.floor(ar)

array([ 0.,  0.,  0.,  0.,  3., 88., -2.])

In [30]:
# rounded to nearest largest integer
np.ceil(ar)

array([ 1.,  1.,  1.,  1.,  4., 89., -1.])

### Trignometric Function

In [31]:
ara

array([ 1,  3,  5, 10])

In [32]:
np.sin(ara)

array([ 0.84147098,  0.14112001, -0.95892427, -0.54402111])

In [33]:
np.sin(np.pi/2)

1.0

In [34]:
np.sin(0)

0.0

In [35]:
np.cos(0)

1.0

In [36]:
np.cos(np.pi/2)

6.123233995736766e-17

In [37]:
# converting radians into functions

In [38]:
np.degrees(np.pi)

180.0

In [39]:
np.arcsin(1)

1.5707963267948966

In [40]:
np.degrees(np.arcsin(1))

90.0

In [41]:
# hypotenuse function for providing base and taking perpendicular height of triangle

In [43]:
np.hypot(3, 4)

5.0

### Logarithmic and Exponential function

In [45]:
np.exp(1)

2.718281828459045

In [46]:
np.exp(2)

7.38905609893065

In [47]:
np.exp([4, 6, 8, 10])

array([   54.59815003,   403.42879349,  2980.95798704, 22026.46579481])

In [48]:
# natural log
np.log(1)

0.0

In [49]:
np.log(np.exp(1))

1.0

In [50]:
np.log10(1)

0.0

In [51]:
np.log10(10)

1.0

In [52]:
np.log2(2)

1.0

### Matrix multiplication use @

In [54]:
ax = np.array([[4, 6, 8, 19], [7, 67, 22, 45]])

In [55]:
ax

array([[ 4,  6,  8, 19],
       [ 7, 67, 22, 45]])

In [56]:
ay = np.array([[4, 6], [82, 11], [34, 1], [14, 10]])

In [57]:
ay

array([[ 4,  6],
       [82, 11],
       [34,  1],
       [14, 10]])

In [ ]:
ax